// List emoji yang akan digunakan pada panel emoji
export const emojiList = [
  { emoji: "😀", name: "Grinning Face" },
  { emoji: "😂", name: "Face with Tears of Joy" },
  { emoji: "😍", name: "Smiling Face with Heart-Eyes" },
  { emoji: "😎", name: "Smiling Face with Sunglasses" },
  { emoji: "😊", name: "Smiling Face with Smiling Eyes" },
  { emoji: "😉", name: "Winking Face" },
  { emoji: "🥰", name: "Smiling Face with Hearts" },
  { emoji: "😘", name: "Face Blowing a Kiss" },
  { emoji: "😇", name: "Smiling Face with Halo" },
  { emoji: "🤔", name: "Thinking Face" },
  { emoji: "😭", name: "Loudly Crying Face" },
  { emoji: "😅", name: "Grinning Face with Sweat" },
  { emoji: "😡", name: "Pouting Face" },
  { emoji: "🥳", name: "Partying Face" },
  { emoji: "😱", name: "Face Screaming in Fear" },
  { emoji: "👍", name: "Thumbs Up" },
  { emoji: "🙏", name: "Folded Hands" },
  { emoji: "👏", name: "Clapping Hands" },
  { emoji: "💪", name: "Flexed Biceps" },
  { emoji: "🎉", name: "Party Popper" },
  { emoji: "❤️", name: "Red Heart" },
  { emoji: "🔥", name: "Fire" },
  { emoji: "✨", name: "Sparkles" },
  { emoji: "🌟", name: "Glowing Star" },
  { emoji: "🌈", name: "Rainbow" },
  { emoji: "☀️", name: "Sun" },
  { emoji: "🌙", name: "Moon" },
  { emoji: "⭐", name: "Star" },
  { emoji: "🍀", name: "Four Leaf Clover" },
  { emoji: "🍕", name: "Pizza" },
  { emoji: "🍔", name: "Hamburger" },
  { emoji: "🍟", name: "French Fries" },
  { emoji: "🍣", name: "Sushi" },
  { emoji: "🍩", name: "Doughnut" },
  { emoji: "⚽", name: "Soccer Ball" },
  { emoji: "🏀", name: "Basketball" },
  { emoji: "🏆", name: "Trophy" },
  { emoji: "🚗", name: "Car" },
  { emoji: "✈️", name: "Airplane" },
  { emoji: "🏠", name: "House" },
  { emoji: "📚", name: "Books" },
  { emoji: "💡", name: "Light Bulb" },
  { emoji: "📅", name: "Calendar" },
  { emoji: "📌", name: "Pushpin" },
  { emoji: "🔒", name: "Lock" },
  { emoji: "🔑", name: "Key" },
  { emoji: "💎", name: "Gem Stone" },
  { emoji: "💰", name: "Money Bag" },
  { emoji: "💯", name: "Hundred Points" },
];
